# Generated by Django 5.2.1 on 2025-12-15 21:37

import app_fsMD.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fsMD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='products/no_image_available.png', upload_to=app_fsMD.models.product_main_image_upload_to),
        ),
    ]
