# Generated by Django 5.2.1 on 2025-12-16 19:23

import app_fsMD.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fsMD', '0002_category_long_description_category_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_fsMD.models.category_image_upload_to),
        ),
    ]
