# Generated by Django 5.2.1 on 2025-12-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fsMD', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('program', 'Program'), ('service', 'Service')], default='program', max_length=10),
        ),
    ]
