# Generated by Django 5.2.1 on 2025-12-26 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fsMD', '0004_category_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='CategoryBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=220)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='app_fsMD.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
