# Generated by Django 5.2.1 on 2025-12-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fsMD', '0005_category_tagline_categorybullet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('testimonial', models.TextField()),
                ('image', models.ImageField(upload_to='feedback_images/')),
                ('star_rating', models.PositiveIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
