# Generated by Django 5.2.1 on 2025-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fsMD', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
