# Generated by Django 5.2.1 on 2025-12-28 17:08

import app_fsMD.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fsMD', '0009_feedback_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('topic', models.CharField(choices=[('weight', 'Weight Management'), ('peptides', 'Peptide Therapy'), ('skin', 'Skin Treatments'), ('hair', 'Hair Health'), ('wellness', 'Wellness Therapy'), ('primary', 'Primary Care')], default='weight', max_length=20)),
                ('badge_label', models.CharField(blank=True, max_length=80)),
                ('excerpt', models.TextField(help_text='Short teaser used on homepage and blog list.')),
                ('body', models.TextField(help_text='Full blog content (HTML or Markdown).')),
                ('main_image', models.ImageField(help_text='Main hero image for this blog.', upload_to=app_fsMD.models.blog_image_upload_to)),
                ('read_time_label', models.CharField(default='4–6 min read', help_text="E.g. '4–6 min read'", max_length=40)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('bullet_1', models.CharField(blank=True, max_length=200)),
                ('bullet_2', models.CharField(blank=True, max_length=200)),
                ('bullet_3', models.CharField(blank=True, max_length=200)),
                ('is_featured_home', models.BooleanField(default=False, help_text="Show in the home 'Latest Health Blogs' block.")),
                ('is_featured_page', models.BooleanField(default=False, help_text='Use as the main feature card on the blog listing page.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this post everywhere.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Manual ordering (lower = higher priority).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
