# Generated by Django 5.2.1 on 2025-12-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fsMD', '0010_blogpost_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text='Short teaser used on homepage and blog listing.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured_home',
            field=models.BooleanField(default=False, help_text="Show in the home 'Latest Health Blogs' section."),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured_page',
            field=models.BooleanField(default=False, help_text='Use as the main feature card on the Blogs & Updates page.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='read_time_label',
            field=models.CharField(default='4–6 min read', help_text="E.g. '4 min read', '6–8 min read'", max_length=40),
        ),
    ]
