# Generated by Django 5.2.1 on 2026-01-01 01:51

import app_fsMD.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fsMD', '0011_alter_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=models.ImageField(help_text='Main hero image for this blog.', max_length=255, upload_to=app_fsMD.models.blog_image_upload_to),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=app_fsMD.models.category_image_upload_to),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(max_length=255, upload_to='feedback_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='products/no_image_available.png', max_length=255, upload_to=app_fsMD.models.product_main_image_upload_to),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to=app_fsMD.models.product_sub_image_upload_to),
        ),
    ]
